### ISSUE TITLE
Low performance when run as a service

### ISSUE THREAD

**Issue by dziban303** [abcd567a/install-aiscatcher#1]
Hi,

Do you have any idea why AIS-catcher may perform dramatically worse when run as a service versus running it manually? If I run it from bash, or with `screen`, or spawned at boot via `rc.local`, I get about 3.5 messages per second. When I run it as a systemd service, using the same settings, I get 1 to 1.5 messages per second. It uses approximately the same amount of CPU cycles as well, as reported by `htop`. I removed the `Nice=-5` line from the unit file but that made no difference. I'm running this on a Raspberry Pi 3B+ running buster
![image](https://user-images.githubusercontent.com/7931765/199150395-3443ba72-8fda-47e6-80e0-2fc016e04059.png)

**Comment by abcd567a** [comment]
I do NOT find any difference in message rate weather I run it manually or through systemd. Please see below the 3rd line of `"CGroup"`. This is part of output of Systemd status command "`sudo systemctl status aiscatcher`". 

Please check if this line in your status output contains all the parameters and values same as in your manual command.

```
CGroup: /system.slice/aiscatcher.service 
├─3221 /bin/bash /usr/share/aiscatcher/start-ais.sh  
└─3223 /usr/local/bin/AIS-catcher -d 00000162 -v 10 -M DT -gr TUNER 38.6 RTLAGC off -s 2304k -p 38 -o 4 -u 127.0.0.1 10110 -u ais.vesselfinder.com xxxx
```

**Comment by dziban303** [comment]
Yep, it's using the same settings. 

```
   CGroup: /system.slice/aiscatcher.service
           ├─574 /bin/bash /usr/local/bin/ais.sh
           └─784 AIS-catcher -M DT -b -v 10 -o 4 -d 162 -s 2304000 -gr rtlagc off biastee on tuner 40 -u 192.168.0.180 10110
```

Compare to htop output of it running manually in screen: 
![image](https://user-images.githubusercontent.com/7931765/199157553-5e1921a7-d018-4cec-ad2e-b40d12adea71.png)

It's a real mystery. It's not a big deal, since I can easily run it on boot via `rc.local` and `screen`, but I'd like to figure out why it's doing this.

**Comment by abcd567a** [comment]
I ran manual command several times over a period of sevrral hours, and each time message rate of manual run and Systemd run were same. Seems your problem is related to something specific in your system.

**Comment by dziban303** [comment]
Yes that was clear from the get go. My question was whether you had any
idea where the problem may be or any pointers. If not that's fine, thank
you for your time!

**Comment by abcd567a** [comment]
If you are using a RTL-SDR Blog V3 dongle with `-gr BIAST on` setting, then using systemd service, the biast wont turn on after AIS-catcher is started, resulting LNA not getting power, and consequent poor performance.

In this case you have to start biast by adding a line `ExecStartPre=/path/to/biast -b 1 -d 0`  above the line  `ExecStart=` in file `/lib/systemd/system/aiscatcher.service`

Note: firts check by `rtl_test-t` what is device number of AIS dongle (0 or 1) and use `- d 0` or `-d 1` in above command accordingly. Remove `BIASTEE on` from `aiscatcher.conf` file

**Comment by dziban303** [comment]
I don't think that's the problem. The bias tee is on, the LED in the LNA lights up. And the decrease is the same with the LNA removed. I gave up on getting this to work, though, it must be some peculiarity with my setup. AIS-catcher also performs poorly when run in docker. I'm content with spawning it on boot through rc.local. I'll close this issue.
