### ISSUE TITLE
Commands to view specific parts of log are changed

### ISSUE THREAD

**Issue by ArTsLeOpS** [abcd567a/install-aiscatcher#10]
The values listed in first column of the table are changed.

Value for PPM is now $17:
`sudo journalctl -u aiscatcher -n 30 | awk -F',' '{print $17}'`
Output:
`"ppm":4.340278
`

Value for Signal Power is now $16:
`sudo journalctl -u aiscatcher -n 30 | awk -F',' '{print $16}'`
Output:
`"signalpower":-46.787212`

**Comment by abcd567a** [comment]
Thank you.
Updated README.md incorporating changes pointed by you.
