### ISSUE TITLE
Stops sending data after a few minutes

### ISSUE THREAD

**Issue by R1ch1e-Lee** [abcd567a/install-aiscatcher#2]
Just setup a new install using this script. Shipxplorer USB dongle and DietPi Linux on an older Emachines PC

After a few minutes (seems to vary but around 15 minutes to 30 minutes) it stops updating positions on sites I send to (marinetraffic, findship).  

systemctl restart aiscatcher fixes the issue until it decides to stop updating again. 

Question is what's the best way to figure out what could be causing this?  I am not too up on which logs or error messages to view to figure out what is happening. 

Thanks in advance

**Comment by R1ch1e-Lee** [comment]
When it stops updating here are a few entries that i have found

This comes up when I remote login the first time when I notice the issue:
curl: (28) Resolving timed out after 3000 milliseconds

Some logs I found when it is not updating:

received: 0 msgs, total: 6108 msgs, rate: 0 msg/s
received: 0 msgs, total: 6108 msgs, rate: 0 msg/s
received: 0 msgs, total: 6108 msgs, rate: 0 msg/s
received: 0 msgs, total: 6108 msgs, rate: 0 msg/s
received: 0 msgs, total: 6108 msgs, rate: 0 msg/s

May 24 12:06:58 DietPi aiscatcher[32358]: RTLSDR: timeout.
May 24 12:06:59 DietPi aiscatcher[32358]: RTLSDR: timeout.
May 24 12:07:01 DietPi aiscatcher[32358]: RTLSDR: timeout.
May 24 12:07:01 DietPi aiscatcher[32358]: [AIS engine v0.45 #0-0]                 received: 0 msgs, total: 6108 msgs, rate: 0 msg/s
May 24 12:07:02 DietPi aiscatcher[32358]: RTLSDR: timeout.
May 24 12:07:04 DietPi aiscatcher[32358]: RTLSDR: timeout.
May 24 12:07:05 DietPi aiscatcher[32358]: RTLSDR: timeout.

When it is working:

May 24 12:13:38 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171338","scaled":true,"channel":"A","nmea":["!AIVDM,1,1,,A,15Nw@V0P0kIdSbfCv>gm;gwp1d00,0*43"],"signalpower":-28.962814,"ppm":3.761574,"mmsi":368038040,"status":0,"status_text":"Under way using engine","turn_unscaled":-128,"turn":-128,"speed":5.100000,"accuracy":false,"lon":-88.133400,"lat":34.904213,"heading":511}
May 24 12:13:40 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171340","scaled":true,"channel":"B","nmea":["!AIVDM,1,1,,B,15NLP@dP00Id<RhD4CN=A?wp0d04,0*45"],"signalpower":-34.374275,"ppm":-2.314815,"mmsi":367468610,"status":12,"status_text":"Reserved","turn_unscaled":-128,"turn":-128,"speed":0.000000,"accuracy":false,"lon":-88.212334,"lat":35.070068,"heading":511}
May 24 12:13:43 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171343","scaled":true,"channel":"B","nmea":["!AIVDM,1,1,,B,15NCv5d000qd2pJD4<3me7ep0PSI,0*09"],"signalpower":-20.842848,"ppm":-1.736111,"mmsi":367328790,"status":12,"status_text":"Reserved","turn_unscaled":0,"turn":0,"speed":0.000000,"accuracy":true,"lon":-88.245316,"lat":35.066906,"heading":246}
May 24 12:13:44 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171344","scaled":true,"channel":"B","nmea":["!AIVDM,1,1,,B,15N0<dg000qd5fvD0siBC`sH0<0:,0*52"],"signalpower":-34.696976,"ppm":-2.893518,"mmsi":367004850,"status":15,"status_text":"Not defined","turn_unscaled":0,"turn":0,"speed":0.000000,"accuracy":true,"lon":-88.235573,"lat":34.978035,"heading":285}
May 24 12:13:47 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171347","scaled":true,"channel":"A","nmea":["!AIVDM,1,1,,A,15NFTTdP00Id0dtD47NVCOwL0@L>,0*79"],"signalpower":-38.345818,"ppm":-4.340278,"mmsi":367371410,"status":12,"status_text":"Reserved","turn_unscaled":-128,"turn":-128,"speed":0.000000,"accuracy":false,"lon":-88.252747,"lat":35.064949,"heading":511}
May 24 12:13:48 DietPi aiscatcher[37910]: [AIS engine v0.45 #0-0]                 received: 5 msgs, total: 234 msgs, rate: 0.499158 msg/s
May 24 12:13:48 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171348","scaled":true,"channel":"B","nmea":["!AIVDM,1,1,,B,35Nw@V0P0lIdSg4Cv>GU8Owp1TeS,0*27"],"signalpower":-25.727745,"ppm":-3.761574,"mmsi":368038040,"status":0,"status_text":"Under way using engine","turn_unscaled":-128,"turn":-128,"speed":5.200000,"accuracy":false,"lon":-88.133171,"lat":34.904049,"heading":511}
May 24 12:13:51 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171351","scaled":true,"channel":"A","nmea":["!AIVDM,1,1,,A,15NLP@dP00Id<RhD4CN77wwp0pN@,0*6C"],"signalpower":-39.379059,"ppm":-2.314815,"mmsi":367468610,"status":12,"status_text":"Reserved","turn_unscaled":-128,"turn":-128,"speed":0.000000,"accuracy":false,"lon":-88.212334,"lat":35.070068,"heading":511}
May 24 12:13:53 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171353","scaled":true,"channel":"A","nmea":["!AIVDM,1,1,,A,15NCv5d000qd2pJD4<3UfWep0W3h,0*17"],"signalpower":-19.029478,"ppm":-1.736111,"mmsi":367328790,"status":12,"status_text":"Reserved","turn_unscaled":0,"turn":0,"speed":0.000000,"accuracy":true,"lon":-88.245316,"lat":35.066902,"heading":246}
May 24 12:13:54 DietPi aiscatcher[37910]: {"class":"AIS","device":"AIS-catcher","rxtime":"20230524171354","scaled":true,"channel":"A","nmea":["!AIVDM,1,1,,A,15N0<dg000qd5fvD0siEuHud068l,0*36"],"signalpower":-41.088467,"ppm":-2.893518,"mmsi":367004850,"status":15,"status_text":"Not defined","turn_unscaled":0,"turn":0,"speed":0.000000,"accuracy":true,"lon":-88.235573,"lat":34.978035,"heading":286}

**Comment by abcd567a** [comment]
(1) It seems hardware problem, (a) either your dongle is failing, or (b) problem is with USB port of your computer. 
Are you using Diet Pi OS through Virtual Machine on Windows? 
The Linux on Windows has often problem of USB Device pass through to Linux OS.

(2) Another source of problem may be DietPI OS itself, which is a stripped-down version of Debian to make it lightweight (hence name "Diet"). It may have some support packages missing, which cause failure.

Anyway the Install script here is only an interface to build and install the Aiscatcher from the source code provided by the site linked below. Please visit there and post your issue there as I don't have any control or contribution to source code.

**https://github.com/jvde-github/AIS-catcher**

**Comment by R1ch1e-Lee** [comment]
Thanks for the reply. 
If I stop the service from running and run AIS-catcher from the command line it works as it should with no issues. So I'm not sure why running as a service would differ than running from command line manually.

**Comment by abcd567a** [comment]
Most likely your aiscatcher.conf file got corrupted  during your manual editing.

Please run installation script again, and when prompted, choose following option to get a fresh copy of config file:

**REPLACE existing config file by default config file**

After installation is completed, **first** run Aiscatcher _**without**_ editing the config file 
by following command, and see if it still fails

`sudo systemctl restart aiscatcher  `

.

**Comment by R1ch1e-Lee** [comment]
Leaving this line out of the aiscatcher.conf file fixed it
-gr TUNER 38.6 RTLAGC off

Not sure why. Maybe it was over driving the dongle then it was failing or losing connection?   

I don't know the gain value I should be using for this dongle but leaving it out is keeping it working.  

I appreciate the steps to try and fix

**Comment by abcd567a** [comment]
Instead of 38, you may try lower values of gain instead of 38.6 in the following line line
-gr TUNER 38.6 RTLAGC off

The acceptable values are from 0.0 to50.0. You can try auto instead of numeric value.

If the problem is nnot solved by reducing gain, then better raise this issue at the Aiscatcher site:

**https://github.com/jvde-github/AIS-catcher**

&nbsp;
