### ISSUE TITLE
Error Line 117

### ISSUE THREAD

**Issue by KD7CAO** [abcd567a/install-aiscatcher#4]
On trying the script and the original manual method, both give me an error. The issue on the script is Line 117. 

git clone https://github.com/jvde-github/AIS-catcher.git

Seems to go part way then time out. 

On a manual pull I get the following out put:

Cloning into 'AIS-catcher'...
remote: Enumerating objects: 21746, done.
remote: Counting objects: 100% (4386/4386), done.
remote: Compressing objects: 100% (1405/1405), done.
error: RPC failed; curl 56 GnuTLS recv error (-9): Error decoding the received TLS packet.
error: 4085 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed

**Comment by abcd567a** [comment]
This error is not error of installation script. It is some issue with AIS-catcher Github site. Please report it there.

By the way, it seems some temporary issue and have resolved. I just now checked, and it is working OK now.

![Screenshot_20240219_163252_Termux](https://github.com/abcd567a/install-aiscatcher/assets/28452511/37174a60-a931-44f2-a651-9ef6a7340f35)
