### ISSUE TITLE
not a bug but a request

### ISSUE THREAD

**Issue by Phil353556** [abcd567a/install-aiscatcher#6]
Hi,

Should it be possible to add the possibility to put comment in the conf file: /usr/share/aiscatcher/aiscatcher.conf ?

something like 

#This is a comment 

Thank You
Phil
see https://discord.com/channels/734090820684349521/869871235092324392

**Comment by abcd567a** [comment]
Sorry, comments cannot be added to aiscatcher.conf. 

Adding anything other than config parameters of AIS-catcher causes it to fail.

**Comment by Phil353556** [comment]
Ok,
What you wrote, confirms my tests :-( 
Is this something that can be enhanced in future?
Thank you

**Comment by abcd567a** [comment]
Yes, this will be a good enhancement, but with my limited Linux knowledge, I am not sure if I can do it. When I find some spare time, I will try.

**Comment by Phil353556** [comment]
ok
How I can help you?
if the # caracter is the caracter used to indicated a line for comment, 
the command grep -v '#'  /usr/share/aiscatcher/aiscatcher.conf ,  will remove those lines.

screenshot for example
![image](https://github.com/abcd567a/install-aiscatcher/assets/64729485/58e0b302-1f84-4a67-9528-71f67f01a223)

Tell me
kind regards
Phil

**Comment by abcd567a** [comment]
Added support for lines with comments, but not by grep-v #, used another method.

To enable this feature, you will need to run the installation script to reinstall aiscatcher with updated version.

**Comment by abcd567a** [comment]
Below is copy of latest version of file `aiscatcher.conf`. As you can see the comments can be placed 
(1) Either as a separate line
(2) Or after aconfig parameter
The option (2) was not possible with `grep -v "#" as it will delete the whole line i.e. both comment and config parameter.

```
-d 00000162  ##dongle serial
-v 10
-M DT
-gr TUNER 38.6 RTLAGC off  ##dongle gain
-s 2304k
-p 3  ##dongle temprature correction, ppm
-o 4
-u 127.0.0.1 10110
## add below url & port number of sites to be fed
## one site per line
-N 8383  #port number to display map in browser
-N PLUGIN_DIR /usr/share/aiscatcher/my-plugins

```

**Comment by Phil353556** [comment]
That's great
Thank you
Phil

**Comment by Phil353556** [comment]
Hi,
The script to upgrade, works like a charm.Thank you!

As it is upgrade, the "reboot pi" is not mandatory. Right?
![image](https://github.com/abcd567a/install-aiscatcher/assets/64729485/a4e1ae06-abf8-48d5-b989-f32a30fe648a)

**Comment by abcd567a** [comment]
No, in case of reinstall / upgrade reboot is not mandatory, but preferable.

**Comment by Phil353556** [comment]
Ok. FYI.  I tested with success without reboot.

**Comment by Phil353556** [comment]
Hi, quick question,  is empty lines are allowed?  (useful to separate standza, for better readability)

example:
#-----------------------------------------------------------
#Device number dongle USB key
 -d 00000001
 
#-----------------------------------------------------------
#Refresh every 10s
 -v 10
 
#-----------------------------------------------------------
#T = NMEA timestamp, D = decoder related (signal power, ppm)
 -M DT

Thank you

**Comment by abcd567a** [comment]
Empty lines are OK.
Try it and see  ;)

**Comment by Phil353556** [comment]
That's nice, thank you. The configuration file is more readable :-)   (sorry for the typo ..., I updated the comment)
