### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by R1ch1e-Lee** [abcd567a/install-aiscatcher#7]
I have 2 working stations using this install script.  

I went to run this script again to get the lastest version, and 1 completed without a hitch and the other I am getting this error:

2024-05-24 14:01:33 (121 KB/s) - written to stdout [7003/7003]

Installing build tools and dependencies...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.18.4-2+deb11u1).
g++ is already the newest version (4:10.2.1-1).
gcc is already the newest version (4:10.2.1-1).
git is already the newest version (1:2.30.2-1+deb11u2).
make is already the newest version (4.3-4.1).
whiptail is already the newest version (0.52.21-4+b3).
libssl-dev is already the newest version (1.1.1w-0+deb11u1).
pkg-config is already the newest version (0.29.2-1).
librtlsdr-dev is already the newest version (0.6.0-3).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-2+deb11u2).
libpq-dev is already the newest version (13.14-0+deb11u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating folder aiscatcher if it does not exist
Creating startup script file start-ais.sh
Writing code to startup script file start-ais.sh
Creating Service file aiscatcher.service
Entering install folder...
code exists
Updating code
Fetching origin
remote: Enumerating objects: 4618, done.
remote: Counting objects: 100% (4618/4618), done.
remote: Compressing objects: 100% (1522/1522), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 315 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
error: Could not fetch origin
[ERROR] Error in line 134 when executing: git fetch --all

Not sure where to go from here

Thanks

**Comment by abcd567a** [comment]
The error is caused by your Pi not able to fetch source code from github server. This is most likely a temporary failure at github server.

Please try to run the install script again after waiting for an hour or two.

**Comment by R1ch1e-Lee** [comment]
Thanks.  I tried again after a day but still fails.  I have no idea why it stops.  It seems to progress normally but just hangs with that error after a few moments. 

code exists
Updating code
Fetching origin
remote: Enumerating objects: 4618, done.
remote: Counting objects: 100% (4618/4618), done.
remote: Compressing objects: 100% (1522/1522), done.
Receiving objects:  74% (3450/4618), 2.54 MiB | 51.00 KiB/s

**Comment by abcd567a** [comment]
When it stops at less than 100% (like 74% in your last message), please wait for few minutes. It will resume operation and complete it.
