### ISSUE TITLE
upgrade not working

### ISSUE THREAD

**Issue by Phil353556** [abcd567a/install-aiscatcher#8]
Hi,
Just upgrade to latest version using the standard install script

Version              v0.59-354-g29cccb06
Build date          Aug 3 2024
Engine                AIS engine      v0.59

got
```
AIS-catcher (build Aug  3 2024) v0.59-354-g29cccb06
(C) Copyright 2021-2024 jvde-github and other contributors
This is free software; see the source for copying conditions.There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Error: syntax error on command line with setting "#". setting does not start with "-"."
```
solved by removing all comment lines, so all lines with '#' 
it works

**Comment by Phil353556** [comment]
ok
I upgraded using command as written in README.md and it works with configuration with comments. Don't understand why it was not working previously.

`sudo bash -c "$(wget -O - https://raw.githubusercontent.com/abcd567a/install-aiscatcher/master/install-aiscatcher.sh)"`

**Comment by abcd567a** [comment]
Glad to know your problem is solved

**Comment by Phil353556** [comment]
Yes, However I don't know exactly what was the issue so strange
