### ISSUE TITLE
Add option to save graph history

### ISSUE THREAD

**Issue by ArTsLeOpS** [abcd567a/install-aiscatcher#9]
Restarting AIS-catcher typically erases history in the graphs. To retain plot "state" and backup the information to a file add in /usr/share/aiscatcher/aiscatcher.conf the following line:
```
-N FILE /usr/share/aiscatcher/my-stats/stat.bin BACKUP 60
```
[Source](https://github.com/jvde-github/AIS-catcher?tab=readme-ov-file#plots)

**Comment by abcd567a** [comment]
Oct 12, 2024
Added following line to file `/usr/share/aiscatcher/aiscatcher.conf` 
`-N FILE /usr/share/aiscatcher/stat.bin BACKUP 60`
It creates a 72.5 KB file `stat.bin` in folder `/usr/share/aiscatcher/`
